[package]
name = "snapatac2-core"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
flate2 = "1.0"
itertools = "0.8"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "cded506230e8d259f7c909df1ef6f53d6fea095a" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "27cedd1aa077ce762ee847249e714f2236c74a1d" }
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
noodles-gff = "0.5"
rayon = "1.5"
nalgebra-sparse = "0.7"
polars = { version = "0.23", features = ["ndarray", "dtype-categorical"] }
indexmap = "1.9"
anyhow = "1.0"
lexical = "6.1"
tempfile = "3.3"
which = "4.2"
bigtools = "0.1"
futures = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false