[package]
name = "snapatac2-core"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
flate2 = "1.0"
itertools = "0.8"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "cded506230e8d259f7c909df1ef6f53d6fea095a" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "39ac1930cc6f50c014e9d53e5346e2058b855f99" }
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
ndarray = { version = "0.15.4", features = ["rayon"] }
num = "0.4.0"
noodles-gff = "0.5.0"
rayon = "1.5.1"
nalgebra-sparse = "0.6.0"
polars = { version = "0.20.0", features = ["ndarray", "dtype-categorical"] }
anyhow = "1.0"
lexical = "6.1"
tempfile = "3.3.0"
which = "4.2"
bigtools = "0.1"
futures = "0.3.23"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
