[package]
name = "snapatac2-core"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "bf0861e3e310b291a864f6ee2f73189c755f13a9" }
anyhow = "1.0"
bigtools = "0.1"
bincode = "1.3"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "204088a9977946b6bbec519f28fd42ae681c51d3" }
extsort = "0.4"
either = "1.8"
flate2 = "1.0"
futures = "0.3"
hdf5 = "0.8"
itertools = "0.8"
indexmap = "1.9"
indicatif = "0.17"
lexical = "6.1"
log = "0.4"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
noodles = { version = "0.27.0", features = ["core", "bam", "sam", "gff"] }
nalgebra-sparse = "0.8"
polars = { version = "0.25", features = ["ndarray", "dtype-categorical"] }
rayon = "1.5"
regex = "1.6"
serde = "1.0"
statrs = "0.16"
tempfile = "3.3"
which = "4.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false