[package]
name = "snapatac2-core"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "4c34e437798f48f279c2c9fc614aa2517fc719d7" }
anyhow = "1.0"
bigtools = "0.1"
bincode = "1.3"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "41e54b2a363f482494ad3e08338f97f93d5e165b" }
extsort = "0.4"
flate2 = "1.0"
futures = "0.3"
itertools = "0.8"
indexmap = "1.9"
indicatif = "0.17"
lexical = "6.1"
log = "0.4"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
noodles = { version = "0.27.0", features = ["core", "bam", "sam", "gff"] }
nalgebra-sparse = "0.7"
polars = { version = "0.23", features = ["ndarray", "dtype-categorical"] }
rayon = "1.5"
regex = "1.6"
serde = "1.0"
statrs = "0.16"
tempfile = "3.3"
which = "4.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false