[package]
name = "snapatac2"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
#snapatac2-core = { git = "https://github.com/kaizhang/SnapATAC2.git", rev = "71b6a6cbfafeb5a5bef0504c9a91937ad88ad904" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "18b40a115d62fd32690f761208f673c6fac691af" }
pyanndata = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "18b40a115d62fd32690f761208f673c6fac691af" }
snapatac2-core = { path = "../snapatac2-core" }
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
#pyanndata = { path = "../../anndata-rs/pyanndata" }
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "5649e8e82af36bb1e35807384fb108c0591a098a" }
itertools = "0.8"
flate2 = "1.0"
hdf5 = "0.8.1"
rayon = "1.5.1"
linreg = "0.2.0"
numpy = "0.16"
ndarray = "0.15.4"
linfa = "0.5.0"
linfa-clustering = "0.5.0"
rand_isaac = "0.3.0"
rand_core = "0.6"
hora = "0.1.1"

[dependencies.pyo3]
version = "0.16.2"
features = ["extension-module"]

[lib]
name = "_snapatac2"
crate-type = ["cdylib"]
