[package]
name = "snapatac2"
version = "2.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
#anndata-rs = { path = "../../anndata-rs/anndata-rs" }
#pyanndata = { path = "../../anndata-rs/pyanndata" }
anndata-rs = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "6e788ec07f560ae5364bd860a0f17294c5993439" }
pyanndata = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "6e788ec07f560ae5364bd860a0f17294c5993439" }
#snapatac2-core = { git = "https://github.com/kaizhang/SnapATAC2.git", rev = "32453ec0598123e4d9aa25884704ee7ebb2bbe7e" }
snapatac2-core = { path = "../snapatac2-core" }
anyhow = "1.0"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "204088a9977946b6bbec519f28fd42ae681c51d3" }
flate2 = "1.0"
hdf5 = "0.8"
hora = "0.1"
itertools = "0.8"
linreg = "0.2"
log = "0.4"
linfa = "0.6"
linfa-clustering = "0.6"
noodles = { version = "0.27.0", features = ["bam", "sam"] }
numpy = "0.17.2"
nalgebra-sparse = "0.8"
ndarray = "0.15"
polars = { version = "0.23", features = ["ndarray", "dtype-categorical"] }
pyo3-log = "0.7"
rand_isaac = "0.3"
rand_core = "0.6"
rayon = "1.5"
statrs = "0.16"
tempfile = "3.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = {version = "0.5", features = ["disable_initial_exec_tls"]}

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "anyhow"]

[lib]
name = "_snapatac2"
crate-type = ["cdylib"]
