name: Continuous integration

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1

    - uses: actions/setup-python@v2
      name: Install Python
      with:
          python-version: '3.10'

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.65.0

    - name: Install dependency
      run: |
        rustup default nightly
        sudo pip install --upgrade pip
        pip install --user pytest hypothesis

    - name: Test Rust package
      run: |
        cd ${GITHUB_WORKSPACE}/snapatac2-core && \
          cargo test --all --no-fail-fast --features anndata-rs/static

    - name: Build Python package
      run: cd ${GITHUB_WORKSPACE}/snapatac2-python && pip install --user .

    - name: Test Python package
      run: pytest ${GITHUB_WORKSPACE}/snapatac2-python/tests -v