name: Run Tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1

    - uses: actions/setup-python@v2
      name: Install Python
      with:
          python-version: '3.10'

    - uses: ./.github/actions/setup-rust
      with:
        cache: true

    - name: Install dependency
      run: |
        sudo pip install --upgrade pip
        pip install --user coverage pytest hypothesis

    - name: Test Rust package
      run: |
        cd ${GITHUB_WORKSPACE}/snapatac2-core
        cargo test --release --all --no-fail-fast

    - name: Test Python package
      run: |
        cd ${GITHUB_WORKSPACE}/snapatac2-python
        pip install -e .
        coverage run -m pytest ${GITHUB_WORKSPACE}/snapatac2-python/tests
        mv .coverage ${GITHUB_WORKSPACE}

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3