name: Continuous integration

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependency
      run: |
        sudo apt-get install -y pandoc
        sudo pip install --upgrade pip
        pip install --user Pygments==2.6.1 sphinx==4.4.0 pandoc nbsphinx \
          sphinx-autodoc-typehints sphinx_rtd_theme myst-parser markupsafe==2.0.1 \
          pytest hypothesis

    - name: Build and test package
      run: |
        cd ${GITHUB_WORKSPACE}/snapatac2-core && \
          cargo test --all --no-fail-fast --features anndata-rs/static
        cd ${GITHUB_WORKSPACE}/snapatac2-python && \
          pip install --user .
        pytest ${GITHUB_WORKSPACE}/snapatac2-python/tests

    - name: Build doc
      run: |
        cd ${GITHUB_WORKSPACE}
        sphinx-build ${GITHUB_WORKSPACE}/docs _build/html

    - name: Upload doc
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./_build/html

  upload_gh-page:
    #if: startsWith(github.ref, 'refs/tags/v')
    name: Publish
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
    - name: Download
      uses: actions/download-artifact@v2

    - name: Upload doc
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
        publish_branch: gh-pages
        force_orphan: true
