name: Build wheels

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - wheels

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    env:
       CIBW_BUILD_VERBOSITY: 1
       CIBW_BEFORE_ALL_LINUX: >
         curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y &&
         yum install -y openssl-devel zlib-devel

       CIBW_ARCHS_LINUX: "auto64"
       CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
       CIBW_SKIP: "cp36-* cp311-* pp* *-win32 *-musllinux*"
       CIBW_TEST_REQUIRES: pytest hypothesis
       CIBW_TEST_COMMAND: "pytest {project}/snapatac2-python/tests"

    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - if: runner.os != 'Linux'
        name: Setup env when not using docker
        run: python -m pip install --upgrade wheel setuptools setuptools-rust

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse snapatac2-python

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install setuptools and setuptools-rust
        run: |
          python -m pip install --upgrade wheel setuptools setuptools-rust

      - name: Build sdist
        run: python setup.py sdist
        working-directory: snapatac2-python

      - uses: actions/upload-artifact@v2
        with:
          path: snapatac2-python/dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}